# Generated by Django 5.2.4 on 2025-07-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
